packaging_format = 2

id = "directorylister"
name = "Directory Lister"
description.en = "Expose the contents of any web-accessible folder for browsing and sharing"
description.fr = "Exposez le contenu de n'importe quel dossier accessible sur le Web pour la navigation et le partage"

version = "4.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.directorylister.com/"
demo = "https://demo.directorylister.com/"
admindoc = "https://docs.directorylister.com/"
code = "https://github.com/DirectoryLister/DirectoryLister"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/directorylister"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        url = "https://github.com/DirectoryLister/DirectoryLister/archive/refs/tags/4.0.0.tar.gz"
        sha256 = "dba5832579cf06d158e8669510b074d1820af31632aa114704f51012b0c19143"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm, php8.2-fileinfo, php8.2-dom, php8.2-zip"
